#!/bin/bash
set -e

# get scripts directory
CMAKE_SOURCE_DIR=$(dirname $(readlink -f $0))
# update cmake source path
CMAKE_SOURCE_DIR=$(pwd)
cd ${CMAKE_SOURCE_DIR}

cmake -B build
cmake --build build -j`nproc`

file_path=$1
./build/${file_path%%\.cc}